apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-monitor-certificate
  namespace: {{ namespace }}
spec:
  secretName: uptime-monitor-tls
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
  dnsNames:
    - {{ hostname }}