version: "3.8"

services:

  uptime-monitor:
    image: ghcr.io/ruchira088/uptime-monitor-api:main
    healthcheck:
      test: "/opt/scripts/wait-for-it.sh localhost:8080"
      start_period: 5s
      interval: 10s
      retries: 10
      timeout: 5s
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/uptime-monitor"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"
    volumes:
      - ./src/main/resources/logback.xml:/opt/data/logback.xml
      - ./docker-compose/scripts:/opt/scripts

  migration:
    image: ghcr.io/ruchira088/uptime-monitor-migration:main
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APPLICATION: "api"
      DATABASE_URL: "jdbc:postgresql://postgres:5432/uptime-monitor"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"
  
  postgres:
    image: postgres
    healthcheck:
      test: "pg_isready -U admin -d uptime-monitor"
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "uptime-monitor"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
