version: "3.8"

services:
  load-balancer:
    image: nginx:stable-alpine
    healthcheck:
      test: "/opt/scripts/wait-for -t 3 localhost:443"
      start_period: 5s
      interval: 5s
      retries: 5
      timeout: 3s
    depends_on:
      uptime-monitor-api:
        condition: service_healthy
    ports:
      - 443:443
    volumes:
      - "./docker-compose/scripts:/opt/scripts"
      - "./nginx/ssl:/etc/ssl"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"

  uptime-monitor-api:
    image: ghcr.io/ruchira088/uptime-monitor-api:main
    healthcheck:
      test: "/opt/scripts/wait-for-it.sh localhost:8080"
      start_period: 5s
      interval: 5s
      retries: 5
      timeout: 3s
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres:5432/uptime-monitor"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"
    volumes:
      - ./src/main/resources/logback.xml:/opt/data/logback.xml
      - ./docker-compose/scripts:/opt/scripts

  migration:
    image: ghcr.io/ruchira088/uptime-monitor-migration:main
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APPLICATION: "api"
      DATABASE_URL: "jdbc:postgresql://postgres:5432/uptime-monitor"
      DATABASE_USER: "admin"
      DATABASE_PASSWORD: "password"
  
  postgres:
    image: postgres
    healthcheck:
      test: "pg_isready -U admin -d uptime-monitor"
      start_period: 5s
      interval: 5s
      retries: 5
      timeout: 3s
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "uptime-monitor"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
