apiVersion: batch/v1
kind: Job
metadata:
  name: data-migration-job-{{ git_branch }}-{{ git_commit }}
  namespace: {{ namespace }}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: docker-registry-credentials
      containers:
        - name: migration-container
          image: ghcr.io/ruchira088/uptime-monitor-migration:{{ git_branch }}-{{ git_commit }}
          envFrom:
            - configMapRef:
                name: migration-config-map
            - secretRef:
                name: migration-secrets