FROM openjdk:17-slim

LABEL org.opencontainers.image.source https://github.com/ruchira088/uptime-monitor

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/uptime-monitor

ADD uptime-monitor-*.tgz .

EXPOSE 8080

CMD [ "/opt/uptime-monitor/bin/uptime-monitor" ]
