FROM openjdk:17-slim

LABEL org.opencontainers.image.source https://github.com/ruchira088/uptime-monitor

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/uptime-monitor-{{ app_name }}

ADD uptime-monitor-{{ app_name }}*.tgz .

{% if ports is defined %}
EXPOSE {{ ports }}
{% else %}
{% endif %}

CMD [ "/opt/uptime-monitor-{{ app_name }}/bin/uptime-monitor-{{ app_name }}" ]