apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: {{ namespace }}
spec:
  selector:
    matchLabels:
      app: api
      branch: {{ git_branch }}
  replicas: 1
  template:
    metadata:
      labels:
        app: api
        branch: {{ git_branch }}
    spec:
      containers:
        - name: api-container
          image: ghcr.io/ruchira088/uptime-monitor-api:{{ git_branch }}-{{ git_commit }}
          envFrom:
            - configMapRef:
                name: api-data-config-map
            - secretRef:
                name: api-secrets
          readinessProbe:
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-readiness-probe
          livenessProbe:
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-liveness-probe
          startupProbe:
            periodSeconds: 5
            failureThreshold: 5
            httpGet:
              port: http4s-port
              path: /service/info
              httpHeaders:
                - name: X-Correlation-ID
                  value: k8s-startup-probe
          ports:
            - name: http4s-port
              containerPort: 8080
          volumeMounts:
            - mountPath: /opt/data
              name: file-config-map
      volumes:
        - name: file-config-map
          configMap:
            name: api-file-config-map
      imagePullSecrets:
        - name: docker-registry-credentials

